@startuml
skinparam sequenceArrowingStyle solid

actor Seller
participant "C2C Marketplace" as System

title UC_01: Product Listing Management

' 1. Seller submits all details for a validation check
Seller -> System: Submits listing for review
activate System

System -> System: Runs Content Moderation Checks


' 2. System responds based on the moderation outcome
alt failure (moderation failed)
    System --> Seller: Returns policy violations
    Seller -> System: Submits revised details 
else success  (moderation passed)
    System --> Seller: Shows listing preview
end

deactivate System

' 3. If validation was successful, the Seller reviews and publishes
    Seller -> System: Reviews & Publishes the listing
    activate System

    System --> Seller: Confirms listing published
    deactivate System


@enduml

