@startuml
skinparam sequenceArrowingStyle solid

actor Buyer
participant "C2C Marketplace" as System

title  UC_04: Personalized Recommendations


note over Buyer,System
Home Page Recommendations
end note




Buyer -> System: Opens Home page
activate System

System -> System: Generates personalized feeds
System -> System: Include Targeted Ads


alt existing user
    System --> Buyer: Shows personalized recommendations
    |||
else new user (cold start)
    System --> Buyer: Shows popular items
    |||
end

deactivate System

|||
|||

note over Buyer,System
Product Detail Page Recommendations
end note




Buyer -> System: Opens a product page
activate System

System -> System: Generates related items for the product
System --> Buyer: Shows recommended Related Items

deactivate System

@enduml
